### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by aghaeian** [damalis/bagisto-iyzico#1]
Merhaba,
Test kartı ile deneme yaparken işlem başarılı tamalandı ancak siteye dönüşte error 500 verdi. 
![Screenshot 2024-10-19 at 15 33 00](https://github.com/user-attachments/assets/da8a1950-5a86-4528-a326-ed019086307e)

**Comment by damalis** [comment]
Merhaba;

En son versiyonu yükleyerek tekrar deneyiniz.

**Comment by aghaeian** [comment]
Yanıtınız için teşekkürler. 
Şimdi de misafir kullanıcı olarak sipariş verirken 5022 kodlu hatanı veriyor. Kayıtlı kullanıcı olarak da ödemeye tıkladıktan sonra checkout linkinde(https://arsalan.tr/iyzico-payment-checkout) kalıyor ve hiçbir bir işlem yapmıyor. ![image](https://github.com/user-attachments/assets/9fafa11d-4976-4552-ac1d-81aee7a01af9)

![image](https://github.com/user-attachments/assets/2a37a8d0-ec8e-4d51-8ac9-4e08ade02770)

**Comment by aghaeian** [comment]
Biligisayrda denedim boş ekranda aslında ödeme sayfası açılmış ama telefonda gözükmüyor. test kart ile işlem yaptım ancak işlemem tamamlanıp boş sepet gösterdi ama admin panelde sipariş oluşmuş olarak gözüküyor. Sandbox tan ödemeyi kontrol edince gözükmüyor.

**Comment by aghaeian** [comment]
birde paynkolay ve papara yıda entegre etme imkanı var mı bu ödeme yöntemine?

**Comment by damalis** [comment]
Merhaba;

5022 hatası çözüldü ve paynkolay ve papara ile ilgili çalışma bulursanız olabilir.

**Comment by aghaeian** [comment]
Teşekkürler. 
Şu an tek sorun mobil tarayıcıda normal durumda kart giriş ekranı gösterilmiyor ama masaüstü modunu aktifleştirdiğin zaman gözüküyor bir de ödeme tamamlandıktan sonra başarılı olmasına rağmen sepet sayfası boş olarak gözüküyor ödeme başarılı ekranı gözükmüyor. 
Ekte papara ve paynkolay dokümanını paylaşıyorum. 
https://paynkolay.com.tr/entegrasyon/entegrasyon
[Papara Merchant Technical Documents.pdf](https://github.com/user-attachments/files/17480130/Papara.Merchant.Technical.Documents.pdf)

**Comment by damalis** [comment]
Merhaba;

Hatalar düzeltildi. Mobil ödeme formu gösterilme durumunu özellikle deneyiniz.

**Comment by aghaeian** [comment]
Merhaba,
Teşekkürler. Sorunlar çözüldü. Sadece cep telefonda ödeme sayfası görülüyor fakat test kart bilgilerini girdikten sonra veri almıyor. Ekran görüntüsü ekte. Normalde bilgileri girdikten sonra taksit olup yada tek çekim gösterir ya işte o veri alınmıyor ve çalışmıyor. 
![image](https://github.com/user-attachments/assets/05634f96-d374-42d4-8dff-f6967aa3be2f)

**Comment by aghaeian** [comment]
Merhaba,
Bunuda ben değiştirdim ziraat için ama ödeme sayfasında bilgileri girdikten sonra teslimat seçeneği göstermiyor ve 500 hatası var konsulda. kontrol etme imkanın var mı?
https://github.com/aghaeian/laravel-pos-ziraat.git
![Screenshot 2024-10-29 at 13 52 58](https://github.com/user-attachments/assets/5f53d395-7f05-4515-aeef-5b12e3cf7b69)

**Comment by aghaeian** [comment]
Özel çalışma imkanınız var mı ziraat bankası için.
